application:
  name: cube-consumer
  topic: test-user-input

spring:
  kafka.consumer:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    group-id: test-user-input-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: com.cube.procon.model
